ludwig-cf/ludwig

- src/ternary_rt.h
> ternary_rt.h

- src/field_phi_init_change.c
i can not create a new file with the same name, so i rename field_phi_init.c to field_phi_init_change.c
> Rename field_phi_init.c to field_phi_init_change.c

- CHANGES.md
- src/ludwig.c
- tests/regression/d3q19-short/serial-chol-st7.log
- version.h
> Release 0.10.0

- src/blue_phase_beris_edwards.c
- src/blue_phase_beris_edwards.h
- src/blue_phase_rt.c
- src/coords_field.c
- src/runtime.c
- src/wall.c
- src/wall.h
- src/wall_rt.c
> Feature cq

- src/colloids_rt.c
> Trap bad number of colloids at run time

- .gitignore
- util/capillary.c
This pull request contains addition of crystalline capillaries (simple cubic crystal - SCC, body-centered cubic crystal - BCC, and face-centered cubic crystal - FCC)  in "util/capillary.c" file.
> implementation of SCC, BCC, and FCC crystalline capillaries

- src/collision.c
> Remove restriction on NSIMDVL in collision related to viscosity model

- src/distribution_rt.c
- src/runtime.c
- src/runtime.h
- tests/regression/d3q19-short/serial-dist-2kh.inp
- tests/regression/d3q19-short/serial-dist-2kh.log
- tests/unit/test_runtime.c
> Add KH initialisation from input

- src/field_s.h
- src/ludwig.c
- src/phi_cahn_hilliard.c
- src/symmetric_rt.c
- src/symmetric_rt.h
The changes proposed here improve the conservation of the order parameter in presence of solid objects. We have observed a slight violation of this conservation in cases of wetting parameter H different from zero. The correction is made at the fluid nodes that are adjacent to the solid ones.
> improving the conservation of the order parameter

- src/fe_ternary.c
- src/gradient_3d_ternary_solid.c
- src/ludwig.c
- src/phi_force.c
enable gradmu method if there is solid, allow to choose between gradmu and divergence (default is gradmu), solid nodes wetting properties introduced using capillary.c file (h->h1, c->h2), correct momentum if ternary free energy is selected
> Feature 3phase

- util/capillary.c
Added option STATUS_WITH_H1_H2 and output solid-liquid contact angles
> Enable STATUS_WITH_H1_H2 for ternary model

- src/Makefile
- util/extract.c
> Minor updates

- Makefile.mk
- config/unix-hipcc.mk
- src/field_grad.c
- src/leesedwards.c
- src/model.c
- src/physics.c
- target/target.h
- target/target_hip.c
- tests/unit/tests.c
> Feature hip

- src/blue_phase_rt.c
- src/colloid_io.c
- src/colloids_halo.c
- src/colloids_rt.c
- src/compiler.c
- src/coords.c
- src/ewald.c
- src/fe_ternary_stats.c
- src/io_harness.c
- src/leesedwards.h
- src/psi_gradients.h
- src/runtime.c
- src/wall.c
- tests/unit/test_colloids_halo.c
- tests/unit/test_phi_ch.c
- util/extract.c
> Fix alerts

- src/coords.c
- src/runtime.c
- src/runtime.h
> Some refactoring to remove problematic scanf etc

- CHANGES.md
- mpi_s/mpi.h
- mpi_s/mpi_serial.c
- src/bbl.c
- src/colloid_sums.c
- src/colloid_sums.h
- src/colloids.h
- src/ludwig.c
- src/phi_force_stress.c
- src/phi_force_stress.h
- src/stats_colloid_force_split.c
- src/stats_colloid_force_split.h
- tests/unit/test_fe_symmetric.c
Pending some additional testing.
> Feature force split

- tests/unit/test_halo.c
- tests/unit/test_hydro.c
Some tests were erroneous in the device version
> Fix logic for host/device halo swaps

- src/distribution_rt.c
- src/field.c
- src/field_options.c
- src/field_options.h
- src/lb_data_options.c
- src/lb_data_options.h
- src/ludwig.c
- src/model.c
Add option for first touch (for host OpenMP).
> Feature first touch

- tests/unit/test_io.c
- util/extract.c
- util/polarizer.c
> Fix fscanf return value alert

- util/extract.c
> Fix one alert

- mpi_s/mpi.h
- mpi_s/mpi_serial.c
- mpi_s/mpi_tests.c
- src/ludwig.c
Remove residual __NVCC__ ifdefs
> Fix issue 215

- src/ludwig.c
- src/model.c
> Fix default host halo swap to full

- CHANGES.md
- src/Makefile
- src/compiler.c
- src/compiler.h
- src/pe.c
- tests/test-diff.sh
Adds commit information and compiler options of the form:
```
Welcome to: Ludwig v0.19.0 (Serial version running on 1 process)
Git commit: 83a1ea4f7d165b824c493ff84ce781f83b127736
Start time: Tue Jan  3 17:29:30 2023
Compiler:
name:           Gnu 10.2.0
version-string: 10.2.0
options:        -O2 -g -Wall -Werror -fopenmp
```
> Add compiler information and hide from tests

- CHANGES.md
- src/hydro_rt.c
- src/model.c
> Feature hydro first touch

- .github/workflows/codecov.yml
- CHANGES.md
- config/coverage-gcc.mk
- mpi_s/Makefile
- src/Makefile
- src/blue_phase_beris_edwards.c
- target/Makefile
- tests/unit/Makefile
- util/Makefile
Added the code-cov workflow description...
> Feature coverage

- src/ludwig.c
> Fix bad LE initialisation possibility

- src/main.c
- src/wall_rt.c
- tests/unit/test_util.c
Moving wall issue.
Also traps command line arguments (file name no longer supported).
> Fix issue 257

- util/extract.c
> Use snprintf

- src/bbl.c
- src/bbl.h
- src/build.c
- src/colloid.c
- src/colloid.h
- src/colloids.c
- src/colloids.h
- src/colloids_rt.c
- src/stats_colloid.c
- src/stats_colloid.h
- src/util_ellipsoid.c
- src/util_ellipsoid.h
First attempt to incorporate ellipsoidal colloids
> Feature ellipsoid

- src/wall.c
> Upate confusing comment on link direction

- CHANGES.md
- codecov.yml
- src/colloids.c
- version.h
Should not be picked up by tests at present.
> Fix for issue 270

- src/colloid_io.c
- src/colloid_io_rt.c
- util/extract.c
- util/extract_colloids.c
> Avoid bad colloid io grid input

- src/colloids_rt.c
> Spherical squirmer initialisation

- src/advection.c
- src/ewald.c
- src/io_impl_mpio.c
- src/wall.c
- tests/unit/test_fe_electro.c
- tests/unit/test_fe_electro_symm.c
- tests/unit/test_kernel_3d.c
- tests/unit/test_kernel_3d_v.c
- tests/unit/test_lb_bc_outflow_rhou.c
- tests/unit/test_psi_solver_options.c
- tests/unit/test_psi_sor.c
> Fix issue 302

- config/unix-nvcc-default.mk
> Add missing target

- src/bbl.c
- src/colloids_rt.c
- src/util.c
- src/util.h
- tests/regression/d2q9/serial-disk-s01.inp
- tests/regression/d2q9/serial-disk-s01.log
> Add dynamic update for 2d disks

- src/bbl.c
The squirmer section for disks.
> Add separate disk squirmer section

- mpi_s/mpi.h
- mpi_s/mpi_serial.c
- mpi_s/mpi_tests.c
For #209 
This has improved the error-handling of the stub mpi; but I have not moved the tests.
> mpi stub tests

- src/gradient_3d_27pt_solid.c
> Colloid wetting problem
